### ISSUE TITLE
env["PATH"] of kernelspec not respected 

### ISSUE THREAD

**Issue by benneti** [emacs-jupyter/jupyter#431]
I have a kernelspec that contains
```
{
  "display_name": "Julia 1.8.5",
  "argv": [
    "/nix/store/jx7893hmfvy3blydwaskd6b101bj2y58-julia-env/bin/julia",
    "-i",
    "--color=yes",
    "/nix/store/ls1bd6gi1jjiqvbsc5dpiy10pgpyqz70-julia-bin-1.8.5-IJulia-1.24.0/share/julia/packages/IJulia/src/kernel.jl",
    "{connection_file}"
  ],
  "language": "julia",
  "env": {
    "PATH": "${PATH}:/nix/store/vwpvhm391n2bqw1pg50f2rw43hhi6zmv-texlive-combined-2021/bin:/nix/store/ysr5xsylz2mianwzv8dln6i5m26yy700-pdf2svg-0.2.3/bin",
    "JULIA_NUM_THREADS": "auto"
  },
  "interrupt_mode": "signal"
}
```
but if I use this kernel in emacs-jupyter the pdf2svg path is not added (it works however with the jupyter console).

**Comment by benneti** [comment]
Actually on rebooting it catched up on the new configuration, however ${PATH} is not expanded correctly, i.e. in emacs I get
`"/run/wrappers/bin:/usr/bin:/usr/sbin:\${PATH}:/nix/store/vwpvhm391n2bqw1pg50f2rw43hhi6zmv-texlive-combined-2021/bin:/nix/store/ysr5xsylz2mianwzv8dln6i5m26yy700-pdf2svg-0.2.3/bin"`
while in the standard jupyter console I get
`/run/wrappers/bin:/usr/bin:/usr/sbin:/nix/store/65cp4izx3bllnwqn7c7dhrq9h9gmjkal-python3-3.10.9/bin:/nix/store/305xcr2qsgff6rj5fdcw7h346684v9mk-python3.10-jupyter_console-6.4.4/bin:/nix/store/big6ccqb03w6ilr819ra9n9mhznv1j6z-python3.10-jupyter_client-7.3.5/bin:/nix/store" ⋯ 355 bytes ⋯ "r-user/benneti/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin:/nix/store/2j81gk0h53pp1fg0nls0kc91acznflc6-fzf-0.35.1/bin:/nix/store/vwpvhm391n2bqw1pg50f2rw43hhi6zmv-texlive-combined-2021/bin:/nix/store/ysr5xsylz2mianwzv8dln6i5m26yy700-pdf2svg-0.2.3/bin`

**Comment by benneti** [comment]
On the next branch not using zmq the PATH is set correctly but I have not yet figured out how to get zmq working on the next branch.

**Comment by nnicandro** [comment]
If you are getting a similar error like https://github.com/nnicandro/emacs-zmq/issues/32 could you pull the `next` branch again. You might have pulled it before I merged in the changes mentioned in that issue. Note you will probably have to delete your local version of `next` first since I've been rebasing on top of `master` and force pushing to that branch.

If its not the same error then I would need more information to figure out what is going wrong. Can you show the error that you are getting if there is one. Does it just hang without any kind of message? What is your system information?

On Emacs 28.2 I'm able to run Org source blocks just fine using the `next` branch and ZMQ.
